### ISSUE TITLE
QUESTION for R package version

### ISSUE THREAD

**Issue by dukinMars** [fusarolimichele/DiAna_cleaning#4]
(1) line 892  "t1 <- Reac[, group:=as.numeric(as.factor(pt))][,.(primaryid,group)] %>% distinct()" 
I found that when running line 893, the R package data.table 1.14.8 shows the following message: "Detected an invalid .internal.selfref, fixed by copying the (shallow) copy of the data.table so that := can add columns by reference at some point in the past. This data.table has been copied in R (or manually created using structure(), etc.). Please avoid operations like names<- and attr<- that may currently (and rarely) copy the entire data.table in R. Instead, use the set* syntax to avoid copying."

**Comment by fusarolimichele** [comment]
Hi @dukinMars, thank you for your help in debugging the script. We are still working on the probabilistic deduplication (line 892), since we have to find the way to perform the comparison between the combinations of primaryids with the limited computing power we have. Anyway, that message is just a warning and does not affect the result
